### ISSUE TITLE
Publish failed on Dotnet ios 

### ISSUE THREAD

**Issue by dingxiaolong** [banditoth/maui-archiver-vscode#12]
Dear :
I am using Apple M1 to develop dotnet iOS project .
I face an error when I try to publish my project .
"/usr/local/share/dotnet/sdk/7.0.311/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(112,5): error NETSDK1139: The target platform identifier ios was not recognized".

My target platform is : "    <TargetFramework>net6.0-ios16.1</TargetFramework>",          I try to change it to net6.0-ios,  net7.0-ios ,but aways face this error .
This can archived well on my Vistual Studio for mac .

Could you help check it please ?
Many thanks.

**Comment by banditoth** [comment]
Hey @dingxiaolong 

In the settings change the target framework from .NET 8 to your project's target framework.
If this does not solve your problem , it seems like your dotnet environment is misconfigured. 
Please follow the discussion at https://github.com/dotnet/maui/issues/9134.

If the problem still persists, open this issue back
