### ISSUE TITLE
Building android on OSX issue with keystorePath and keyAlias

### ISSUE THREAD

**Issue by frank-ami-ict** [banditoth/maui-archiver-vscode#13]
When publishing or checking the keystore the file name results in the path being combined twice, and keyAlias always seems to to return null.

**Comment by msrockswell** [comment]
same problems here. iOS works fine.
![Bildschirmfoto 2024-04-16 um 12 05 02](https://github.com/banditoth/maui-archiver-vscode/assets/85175911/70fbe2f9-a90e-47f6-9d6a-8b3abec2d28d)

**Comment by banditoth** [comment]
Fixed in 1.1.1
