### ISSUE TITLE
`Publish iOS` builds using `.net8-ios` when project supports `.net9-ios`

### ISSUE THREAD

**Issue by mcumming** [banditoth/maui-archiver-vscode#14]
My project uses the following:
```msbuild
     <TargetFramework>net9.0-ios</TargetFramework>
```
This is the output from `Publish iOS`
```
dotnet publish "TestApp.iOS.csproj" -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64  -p:CodesignKey="XXX" -p:CodesignProvision="XXX"
```

**Comment by banditoth** [comment]
Hey @mcumming , in the extension settings, you can override the .net version to use

**Comment by banditoth** [comment]
Hey @mcumming 
Since I have not heard from you, I'm closing this issue. Please reopen if the error persists.
