### ISSUE TITLE
Command 'MAUI Archive: Android - List of Keystores & Check signature' resulted in an error

### ISSUE THREAD

**Issue by rajagopalannairr** [banditoth/maui-archiver-vscode#18]
<img width="260" alt="Screenshot 2024-07-13 at 11 51 58 AM" src="https://github.com/user-attachments/assets/0a7ef873-4547-4c91-8b20-6853008d5802">

When I try to archive the Android app (MAUI) from Visual Studio Code for MAC. I am getting the above error. 
Please do the needful.

**Comment by Dardev12** [comment]
Same Error for me too

**Comment by banditoth** [comment]
Hello @rajagopalannairr @Dardev12 ,

If you are still facing this issue, make sure that the correct path to the keystores have been set by opening up the command palette (CMD Shift P) and type '> MAUI Archiver: Settings'
There should be an Android keystore Directory option

![image](https://github.com/user-attachments/assets/a73ef3a7-2de5-40df-a960-dbbc6643f6d2)

Sometimes the Keystores are placed here:
/Users/banditoth/Library/Developer/Xamarin/Keystore/

Please open this issue again if the problem still persists.
